[book]
authors = ["Adeoye Adefemi"]
language = "en"
multilingual = false
src = "src"
title = "Carbonyl API documentation"

[output.html]
default-theme = "light"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/opeolluwa/carbonyl"